using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MultiSupplierMTPlugin.Helpers
{

    class LanguageHelper
    {
        // Copy form MemoQ.Languages.dll (MemoQ.Languages.Resources.Languages.resources)
        public static readonly Dictionary<string, string> CodeToFriendlyNameDic = new Dictionary<string, string>
        {
            { "afr", "Afrikaans" },
            { "aka", "Akan" },
            { "alb", "Albanian" },
            { "alb-AL", "Albanian (Albania)" },
            { "alb-ME", "Albanian (Montenegro)" },
            { "alb-MK", "Albanian (Macedonia)" },
            { "alb-XK", "Albanian (Kosovo)" },
            { "amh", "Amharic" },
            { "apw", "Apache, Western" },
            { "ara", "Arabic" },
            { "ara-AE", "Arabic (U.A.E.)" },
            { "ara-BH", "Arabic (Bahrain)" },
            { "ara-DZ", "Arabic (Algeria)" },
            { "ara-EG", "Arabic (Egypt)" },
            { "ara-IQ", "Arabic (Iraq)" },
            { "ara-JO", "Arabic (Jordan)" },
            { "ara-KW", "Arabic (Kuwait)" },
            { "ara-LB", "Arabic (Lebanon)" },
            { "ara-LY", "Arabic (Libya)" },
            { "ara-MA", "Arabic (Morocco)" },
            { "ara-OM", "Arabic (Oman)" },
            { "ara-QA", "Arabic (Qatar)" },
            { "ara-SA", "Arabic (Saudi Arabia)" },
            { "ara-SY", "Arabic (Syria)" },
            { "ara-TN", "Arabic (Tunisia)" },
            { "ara-YE", "Arabic (Yemen)" },
            { "arg", "Aragonese" },
            { "asm", "Assamese" },
            { "ast", "Asturian" },
            { "atj", "Atikamekw" },
            { "aze", "Azeri (Latin)" },
            { "azf", "Azeri (Cyrillic)" },
            { "baq", "Basque" },
            { "bcr", "Babine-Witsuwit'en" },
            { "bel", "Belarusian" },
            { "ben", "Bengali" },
            { "ben-BD", "Bengali (Bangladesh)" },
            { "ben-IN", "Bengali (India)" },
            { "bis", "Bislama" },
            { "bla", "Blackfoot" },
            { "boc", "Bosnian (Cyrillic)" },
            { "bos", "Bosnian (Latin)" },
            { "bre", "Breton" },
            { "bul", "Bulgarian" },
            { "bxg", "Bangala" },
            { "cat", "Catalan" },
            { "ceb", "Cebuano" },
            { "cgl", "Montenegrin (Latin)" },
            { "cgy", "Montenegrin (Cyrillic)" },
            { "chk", "Chuukese" },
            { "cho", "Choctaw" },
            { "chp", "Dene" },
            { "chr", "Cherokee (Latin)" },
            { "ckb", "Kurdish (Arabic)" },
            { "cre", "Cree (Latin)" },
            { "crg", "Michif" },
            { "crk", "Cree, Eastern (Syllabics)" },
            { "crl", "Cree, Western (Syllabics)" },
            { "ctd", "Chin" },
            { "cze", "Czech" },
            { "dan", "Danish" },
            { "dgr", "Dogrib" },
            { "din", "Dinka" },
            { "dut", "Dutch" },
            { "dut-BE", "Dutch (Belgium)" },
            { "dut-NL", "Dutch (Netherlands)" },
            { "eky", "Kayah (Myanmar)" },
            { "eng", "English" },
            { "eng-AU", "English (Australia)" },
            { "eng-BZ", "English (Belize)" },
            { "eng-CA", "English (Canada)" },
            { "eng-CB", "English (Caribbean)" },
            { "eng-GB", "English (United Kingdom)" },
            { "eng-IE", "English (Ireland)" },
            { "eng-JM", "English (Jamaica)" },
            { "eng-NZ", "English (New Zealand)" },
            { "eng-PH", "English (Philippines)" },
            { "eng-TT", "English (Trinidad and Tobago)" },
            { "eng-US", "English (United States)" },
            { "eng-ZA", "English (South Africa)" },
            { "eng-ZW", "English (Zimbabwe)" },
            { "epo", "Esperanto" },
            { "est", "Estonian" },
            { "fas", "Farsi" },
            { "fat", "Fanti" },
            { "fij", "Fijian" },
            { "fil", "Filipino" },
            { "fin", "Finnish" },
            { "fit", "Meänkieli" },
            { "fre", "French" },
            { "fre-02", "French (Africa)" },
            { "fre-BE", "French (Belgium)" },
            { "fre-CA", "French (Canada)" },
            { "fre-CH", "French (Switzerland)" },
            { "fre-FR", "French (France)" },
            { "fre-LU", "French (Luxembourg)" },
            { "fre-MA", "French (Morocco)" },
            { "fre-MC", "French (Monaco)" },
            { "fry", "Frisian, Western" },
            { "ful", "Fulah" },
            { "ger", "German" },
            { "ger-AT", "German (Austria)" },
            { "ger-CH", "German (Switzerland)" },
            { "ger-DE", "German (Germany)" },
            { "ger-LI", "German (Liechtenstein)" },
            { "ger-LU", "German (Luxembourg)" },
            { "gil", "Kiribati" },
            { "gla", "Gaelic (Scotland)" },
            { "gle", "Irish" },
            { "glg", "Galician" },
            { "gre", "Greek" },
            { "grn", "Guarani" },
            { "guj", "Gujarati" },
            { "hat", "Haitian Creole" },
            { "hau", "Hausa" },
            { "haw", "Hawaiian" },
            { "haz", "Hazaragi" },
            { "heb", "Hebrew" },
            { "hil", "Hiligaynon" },
            { "hin", "Hindi" },
            { "hmn", "Hmong" },
            { "hop", "Hopi" },
            { "hrv", "Croatian" },
            { "hun", "Hungarian" },
            { "hye", "Armenian" },
            { "ibo", "Igbo" },
            { "ice", "Icelandic" },
            { "ike", "Inuktitut, Eastern (Latin)" },
            { "ikf", "Inuktitut, Eastern (Syllabics)" },
            { "ikg", "Inuktitut, Western (Syllabics)" },
            { "ikt", "Inuktitut, Western (Latin)" },
            { "ilo", "Ilocano" },
            { "ind", "Indonesian" },
            { "ita", "Italian" },
            { "ita-CH", "Italian (Switzerland)" },
            { "ita-IT", "Italian (Italy)" },
            { "jav", "Javanese" },
            { "jpn", "Japanese" },
            { "kal", "Greenlandic" },
            { "kan", "Kannada" },
            { "kas", "Kashmiri" },
            { "kat", "Georgian" },
            { "kaz", "Kazakh" },
            { "kea", "Kabuverdianu" },
            { "khk", "Mongolian (Cyrillic)" },
            { "khm", "Khmer" },
            { "kin", "Rwanda" },
            { "kir", "Kyrgyz (Cyrillic)" },
            { "kmr", "Kurdish (Cyrillic)" },
            { "kor", "Korean" },
            { "ksw", "Karen" },
            { "kur", "Kurdish (Latin)" },
            { "kyu", "Kayah (Latin)" },
            { "lao", "Lao" },
            { "lat", "Latin" },
            { "lav", "Latvian" },
            { "lin", "Lingala" },
            { "lit", "Lithuanian" },
            { "lkt", "Lakota" },
            { "ltz", "Luxembourgish" },
            { "mac", "Macedonian" },
            { "mah", "Marshallese" },
            { "mal", "Malayalam" },
            { "mar", "Marathi" },
            { "mic", "Mi'kmaq" },
            { "mlg", "Malagasy" },
            { "mlt", "Maltese" },
            { "mnk", "Mandinka (Latin)" },
            { "mno", "Mandinka (Arabic)" },
            { "mnw", "Mon" },
            { "moe", "Innu" },
            { "moh", "Mohawk" },
            { "mol", "Moldavian" },
            { "mri", "Maori" },
            { "msa", "Malay" },
            { "mya", "Burmese" },
            { "nau", "Nauruan" },
            { "nav", "Navajo" },
            { "nep", "Nepali" },
            { "nnb", "Norwegian (Bokmål)" },
            { "nno", "Norwegian (Nynorsk)" },
            { "nor", "Norwegian" },
            { "oci", "Occitan" },
            { "ocs", "Aranese" },
            { "ojg", "Ojibwa (Syllabics)" },
            { "oji", "Ojibwa (Latin)" },
            { "ori", "Oriya" },
            { "orm", "Oromo" },
            { "pan", "Punjabi (Gurmukhi)" },
            { "pbu", "Pashto" },
            { "pdc", "Pennsylvania German" },
            { "pdt", "Plautdietsch" },
            { "pga", "Sudanese Creole Arabic" },
            { "pis", "Pijin" },
            { "pnb", "Punjabi (Shahmukhi)" },
            { "pol", "Polish" },
            { "pon", "Pohnpeian" },
            { "por", "Portuguese" },
            { "por-BR", "Portuguese (Brazil)" },
            { "por-PT", "Portuguese (Portugal)" },
            { "prs", "Dari" },
            { "qqq", "Klingon" },
            { "quz", "Quechua" },
            { "rhg", "Rohingya" },
            { "rki", "Rakhine" },
            { "rum", "Romanian" },
            { "run", "Rundi" },
            { "rus", "Russian" },
            { "san", "Sanskrit" },
            { "scc", "Serbian (Cyrillic)" },
            { "scr", "Serbian (Latin)" },
            { "shn", "Shan" },
            { "sin", "Sinhala" },
            { "slo", "Slovak" },
            { "slv", "Slovenian" },
            { "smo", "Samoan" },
            { "som", "Somali" },
            { "som-DJ", "Somali (Djibouti)" },
            { "som-ET", "Somali (Ethiopia)" },
            { "som-KE", "Somali (Kenya)" },
            { "som-SO", "Somali (Somalia)" },
            { "sot", "Sesotho" },
            { "spa", "Spanish" },
            { "spa-AR", "Spanish (Argentina)" },
            { "spa-BO", "Spanish (Bolivia)" },
            { "spa-CL", "Spanish (Chile)" },
            { "spa-CO", "Spanish (Colombia)" },
            { "spa-CR", "Spanish (Costa Rica)" },
            { "spa-DO", "Spanish (Dominican Republic)" },
            { "spa-EC", "Spanish (Ecuador)" },
            { "spa-ES", "Spanish (Spain)" },
            { "spa-GT", "Spanish (Guatemala)" },
            { "spa-HN", "Spanish (Honduras)" },
            { "spa-M9", "Spanish (Latin America)" },
            { "spa-MX", "Spanish (Mexico)" },
            { "spa-NI", "Spanish (Nicaragua)" },
            { "spa-PA", "Spanish (Panama)" },
            { "spa-PE", "Spanish (Peru)" },
            { "spa-PR", "Spanish (Puerto Rico)" },
            { "spa-PY", "Spanish (Paraguay)" },
            { "spa-SV", "Spanish (El Salvador)" },
            { "spa-US", "Spanish (United States)" },
            { "spa-UY", "Spanish (Uruguay)" },
            { "spa-VE", "Spanish (Venezuela)" },
            { "sto", "Stoney" },
            { "sun", "Sundanese" },
            { "swa", "Swahili" },
            { "swe", "Swedish" },
            { "swe-FI", "Swedish (Finland)" },
            { "swe-SE", "Swedish (Sweden)" },
            { "tam", "Tamil" },
            { "tat", "Tatar" },
            { "tcs", "Torres Strait Creole" },
            { "tdt", "Tetun Dili" },
            { "tel", "Telugu" },
            { "tgk", "Tajiki (Cyrillic)" },
            { "tgl", "Tagalog" },
            { "tha", "Thai" },
            { "tir", "Tigrigna" },
            { "ton", "Tongan" },
            { "tpi", "Tok Pisin" },
            { "tsn", "Tswana" },
            { "tuk", "Turkmen (Latin)" },
            { "tur", "Turkish" },
            { "tvl", "Tuvaluan" },
            { "twi", "Twi" },
            { "tzm", "Tamazight" },
            { "ukr", "Ukrainian" },
            { "urd", "Urdu" },
            { "uzb", "Uzbek (Latin)" },
            { "uzn", "Uzbek (Cyrillic)" },
            { "vie", "Vietnamese" },
            { "vls", "Flemish" },
            { "wel", "Welsh" },
            { "wol", "Wolof" },
            { "xho", "Xhosa" },
            { "yid", "Yiddish" },
            { "ymm", "Maay" },
            { "yor", "Yoruba" },
            { "zho", "Chinese" },
            { "zho-CN", "Chinese (PRC)" },
            { "zho-HK", "Chinese (Hong Kong S.A.R.)" },
            { "zho-MO", "Chinese (Macao S.A.R.)" },
            { "zho-SG", "Chinese (Singapore)" },
            { "zho-TW", "Chinese (Taiwan)" },
            { "zul", "Zulu" },
        };

        public static readonly Dictionary<string, string> CodeToGlossaryFieldNameDic;

        public static readonly Dictionary<string, string> GlossaryFieldNameToCodeDic;

        static LanguageHelper()
        {
            CodeToGlossaryFieldNameDic = CodeToFriendlyNameDic.ToDictionary(
                kv => kv.Key,
                kv => kv.Value.Replace("(", "").Replace(")", "").Replace(' ', '_'));

            GlossaryFieldNameToCodeDic = CodeToGlossaryFieldNameDic.ToDictionary(kv => kv.Value, kv => kv.Key);
        }
    }

}
